name: flutter_smart_home_tablet
description: Flutter ARS BANK Tablet Application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  collection: ^1.18.0
  skeletonizer: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - assets/mock_data/response/
    - assets/images/
    - lib/feature/warehouse/parent/assets/images/
    - lib/feature/warehouse/parent/assets/mock_data/response/
