name: engo_terminal_app3
description: Flutter ARS BANK Tablet Application.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  get_storage: ^2.1.1
  dio: ^5.7.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  collection: ^1.18.0
  shimmer: ^3.0.0
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  camera: ^0.11.0+2
  fl_chart: ^0.69.0
  intl: ^0.19.0

dependency_overrides:
  camera_android_camerax: 0.6.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true

  assets:
    - lib/wh/feature/warehouse/parent/assets/images/
    - lib/wh/feature/warehouse/parent/assets/images/common/
    - lib/wh/feature/warehouse/parent/assets/images/light/
    - lib/wh/feature/warehouse/parent/assets/images/dark/
    - lib/wh/feature/warehouse/parent/assets/mock_data/response/
